### PR TITLE
Add missing information for data_tag

### PR DESCRIPTION
**Pull request by pavlis**
This is a change only to mspass.yaml to fix an unambiguous mistake in mspass schema.  I found this by running clean_collection in the short course tutorial and found it cleared data_tag I had set in the save.  I wasn't sure if that attribute should be tagged "normal" or "optional".   I set it "normal", but am a bit fuzzy on the distinction

### CODE REVIEW

**Comment by haruming** [comment]
I think the distinction between normal and optional is, normal is the attribute that doesn't hurt the workflow if it doesn't exist in the object, but it would be great if the object contains this attribute. And optional is the attribute that is the lowest priority in the object. I think for data_tag, it's fine for either normal or optional. By the way, we may probably add data_tag in the mspass_lite.yaml, shall we?

**Comment by wangyinz** [comment]
Yes, I agree, and I think data tag should be optional according to the definition. I think the distinction is (at least when we first implement it) that when a normal attribute is missing, we kill the object but does not abort the workflow. 

We definitely need it in the `mspass_lite.yaml`, too, if we are adding it to the `mspass.yaml`

**Comment by wangyinz** [comment]
Yes, I agree, and I think data tag should be optional according to the definition. I think the distinction is (at least when we first implement it) that when a normal attribute is missing, we kill the object but does not abort the workflow. 

We definitely need it in the `mspass_lite.yaml`, too, if we are adding it to the `mspass.yaml`

**Comment by haruming** [comment]
I changed the constraint to optional and also added the attribute in the mspass_lite.yaml. Hopefully, it's ready to merge.

**Pull request merged**
