### PR TITLE
Extend window data

### PR DESCRIPTION
**Pull request by pavlis**
This set of changes implements suggestions proposed in issue #551.   This also required very large changes to the pytest file for the WindowData function.   I think the revisions are pretty complete, but we should review the coverage data before this is merged.   It passed pytest locally so hopefully the only holdup may be in any missed coverage.

### CODE REVIEW

**Comment by pavlis** [comment]
The previous commit had no real errors but I had neglected to remove the debug scaffolding.   The version I just pushes fixes that mistake and should pass tests cleanly.    

The black formatter was detecting an error in this pull request but the error is not mine.  It is in db/client.py.   I think it is a relic of a last minute change before the Earthscope short course. @wangyinz  you may want to resolve that issue either in this branch or separately,.

**Comment by wangyinz** [comment]
This looks good to me and I have merged the black format fix here since this is more straightforward. The coverage is only at 86.02%, but I think that is good enough.

**Comment by wangyinz** [comment]
I fixed a minor issue on the inconsistent `alg_name`. There is still one issue: the `alg_name` of `WindowDataAtomic` will always be overridden and changed to `WindowData`, but I think this might be OK. What do you think?

**Comment by pavlis** [comment]
I hadn't noticed that about `alg_name` but I see what you mean.   I think your changes handle this correctly,  If you run `WindowData` the `alg_name` will be set as "WindowData" by default but if you run `WindowDataAtomic` directly it gets set to "WindowDataAtomic".   I didn't actually test that but I think that is what will happen.   Hence, I think this is good.  

I also see now the coverage missed by the test functions.   All are rare but probably should be verified.   I'd kind of prefer to punt them down the road.   One is incorrect because the coverage gizmo can't know that the C++ functions should never throw an exception because the python wrappers detect and handle those issues preventing the C++ functions from ever being called with bad input.   the comments around the error handler note that point which is about the best we can do.  

So, I suggest you merge this unless you think I need to add test code for those uncovered error handlers.

**Comment by pavlis** [comment]
@wangyinz hold off on merging this until I tell you it is ok.  I may have found an off by one error in the "pad" mode.

**Comment by pavlis** [comment]
There is indeed a problem.    It is subtle floating point problem the tests didn't detect that effects the new algorithm for both "pad" and "truncate" mode.   It uses a floating point test for < or > of a window timer compared to data start or end time.   The actual interval needs to be rounded to the nearest sample.   When data come from UTC clocks the data start times are not synchronously sampled to the sample grid.   My tests didn't detect that because I was only using simulation data with synchronously sampled data.  

Let me fix this problem and extend the tests to handle the issue.   I'll try to improve the coverage since I need to repair the test functions anyway.   Glad I tried this on the new cross correlation stuff or I wouldn't have detected this problem.

**Comment by pavlis** [comment]
Almost have this but while I remember note that the coverage gizmo is wrong about coverage.  The tests I have for arguments are flagged as untested but they actually are tested.  The problem is that they are actually intercepted by the decorators and whatever approach that gizmo uses it is confused by the redundant error handlers.  Consequently, all I'm adding for the next revisions is a test where I dither the start time by a fraction of a sample.

**Comment by pavlis** [comment]
I fixed the somewhat minor issue to have the WindowData function preserve subsample timing.  Before we merge this though there is a point of discussion to consider.   The current implementation for ensembles has an undesirable side effect that I think is a bad idea.   In particular, this block of code runs the atomic version of window data on each member:
```
for i in range(len(mspass_object.member)):
                if mspass_object.member[i].live:
                    mspass_object.member[i] = WindowDataAtomic(
                        mspass_object.member[i],
                        win_start,
                        win_end,
                        t0shift=t0shift,
                        short_segment_handling=short_segment_handling,
                        log_recoverable_errors=log_recoverable_errors,
                        object_history=object_history,
                        alg_name=alg_name,
                        alg_id=alg_id,
                        dryrun=dryrun,
                    )
```
Because it uses the construct 
```
mspass_object.member[i] = WindowData()
```
and `mspass_object` is the input that does an in place modification.   That reduces memory footprint, which can be a factor with large ensembles as we know, but has an undesirable side effect that if you use a construct like this:
```
enscut = WindowData(ens,stime,etime)
```
after that runs enscut and ens will be references to the same object.  

That is definitely the wrong default behavior, but I could see making that an option.   If you concur I will add an "in_place_return" option for ensembles that would be False by default.   True would probably be the preferred option for map operators.

**Comment by wangyinz** [comment]
Yeah, we shouldn't do in place return here. I think making that an option is definitely needed.

**Comment by pavlis** [comment]
Ok, fixed that last problem.   I probably should have added a test for the new option, which I elected to actually call "overwrite_members" out of fear the symbol would collide with what I suggested above that is used in the mspass_func_decorator.   Probably wouldn't have mattered but I think that name is clearer anyway.  

I think this should be ready to merge now

**Comment by pavlis** [comment]
This branch should be ready to merge.   The latest push was just a trivial format fix with black.   This should resolve the subtle rounding problem with the previous version we discussed in our last group meeting,.

**Pull request merged**
