### PR TITLE
feat: make seisbench dependency optional 

### PR DESCRIPTION
**Pull request by JiaoMaWHU**
## What
To make the `seisbench` dependency optional so that the size of the standard installment can be reduced.

## Next steps:
Also need to update the container definition as part of this pr, so that dev container can have seisbench installed

## Testing
Ran the following commands and verified seisbench is not installed in the first one
```
python3 -m pip install .
python3 -m pip install '.[seisbench]'
```

### CODE REVIEW

**Comment by wangyinz** [comment]
I reran the test in this branch and it failed too. So, there is probably something changed from the remote data.

**Comment by JiaoMaWHU** [comment]
> I reran the test in this branch and it failed too. So, there is probably something changed from the remote data.

Let me take a look. We can consider revert this commit and see if that would fix the issue.

**Comment by JiaoMaWHU** [comment]
@wangyinz please take a look at https://github.com/mspass-team/mspass/pull/580

**Comment by wangyinz** [comment]
Oh, I said already there is probably something wrong in seisbench's server. I don't think reverting this PR will do anything. It is going to fail regardless. I think we just need to remove the dependency of its remote ML model.

**Pull request merged**
